### ISSUE TITLE
Getting no mountable file system error executing the latest MBPMid2010-GPU-Fix-0.6.0.dmg

### ISSUE THREAD

**Issue by my4yahoo** [julian-poidevin/MBPMid2010_GPUFix#52] opened 2017-12-09 21:05 UTC
Hi Julian,

Thanks for making this utility to make it easy to change the kernel configuration, I very much appreciate it.

I am getting no mountable file system error when executing your latest executable. I am able to successfully execute your previous version 0.5.0. My OS version is 10.11.6 and model of the mac is MacBook Pro (15-inch, Mid 2010). 

I tried this but the same result
hdiutil attach ./MBPMid2010-GPU-Fix-0.6.0.dmg
expected   CRC32 $36F3AE43
hdiutil: attach failed - no mountable file systems

Thanks

**Comment by julian-poidevin** [comment] 2017-12-09 22:39
As said in https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/45, I recommend downloading the [ZIP](https://github.com/julian-poidevin/MBPMid2010_GPUFix/releases/download/v0.6.0/MBPMid2010-GPU-Fix-0.6.0.zip) version of the software. The problem is not related to my app bu to your computer, closing the issue.

**Closed by julian-poidevin** 2017-12-09 22:39 UTC
