### ISSUE TITLE
Unable to patch 15-inch 2010 MacBook Pro on High Sierra

### ISSUE THREAD

**Issue by jeromydp** [julian-poidevin/MBPMid2010_GPUFix#35] opened 2017-10-09 17:24 UTC
I'm getting the following message:
| Checking compatibility
MBPModelVersion : MacBookPro6,2 ➔ Compatibility : OK ✓
| Checking SIP Status
SIP Disabled
| Searching for AppleGraphicsPowerManagement.kext
AppleGraphicsPowerManagement.kext found
********** Starting MBP GPU Fix **********
Copying Info.plist file
Previous Info.plist file removed
Could not open Info.plist file
********************* MBP GPU Fix FAILED *********************

**Comment by julian-poidevin** [comment] 2017-10-09 20:42
Hi,

Did you try the app on a previous version of macOS before updating to High Sierra ?

After patch failure, can you please go to `/tmp/` directory and see if there is a file named `PatchedInfo.plist` in it. If so, let me know if you are able to open the file by double-clicking on it.

Also, before running the patch, you can also try to remove all the files in `/tmp/` folder.

Thanks.

**Comment by mhamzas** [comment] 2017-10-17 18:24
It worked fine for me on High Sierra

**Comment by mhamzas** [comment] 2017-10-23 13:13
Try applying patch twice.
On 10/23/2017 6:12:28 PM, kickass-id <notifications@github.com> wrote:
For me, I got MBP GPU Fixed Successfully but it doesn't seem to work (also MBP 15" mid-2010, High Sierra). After applying the patch (log below), I excitedly open IMDB using Safari, and my laptop crashed :(
| Checking compatibility
MBPModelVersion : MacBookPro6,2 ➔ Compatibility : OK ✓
| Checking SIP Status
SIP Disabled
| Searching for AppleGraphicsPowerManagement.kext
AppleGraphicsPowerManagement.kext found
********** Starting MBP GPU Fix **********
Copying Info.plist file
Patching Info.plist
- FindChild - key|MacBookPro6,2
- NextSibling - dict
- FindChild - key|LogControl
- ModifyIntValue - integer|1
- FindSibling - key|Vendor10deDevice0a29
- FindSibling - key|BoostPState
- FindSibling - key|BoostTime
- FindSibling - key|Heuristic
- FindSibling - key|IdleInterval
- ModifyIntValue - integer|10
- RemoveSiblingLabel - P3HistoryLength Not found
- FindSibling - key|SensorSampleRate
- ModifyIntValue - integer|10
- FindSibling - key|Threshold_High
- FindSibling - key|Threshold_High_v
- FindSibling - key|Threshold_Low
- FindSibling - key|Threshold_Low_v
Info.plist successfully patched
| Loading Kernel Extension
Removing existing kext in tmp : ✓
Copying actuel kext into tmp : ✓
Copying patched Info.plist into kext : ✓
Changing permission of kext : ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext
Removing existing kext : ✓
Copying patched kext into Extension : ✓
Loading modified kext : ✓
********************* MBP GPU Fixed Successfully *********************

**Comment by kickass-id** [comment] 2017-10-23 15:24
After applying the patch twice, my laptop hasn't crashed ever since. I have Android Studio opened (usually it's instant-crash). What kind of sorcery is this!!! :D

**Comment by julian-poidevin** [comment] 2017-10-23 15:41
The Mac is just a bit less performant and it does not work if you are using an external screen. These are the only two downsides.

**Comment by mhamzas** [comment] 2017-10-23 19:14
@kickass-id , The same happened to me and I thought that may be it didn't get applied. After crashing I tried and it worked.   
That's strange but some how I make it work :p

**Comment by mhamzas** [comment] 2017-10-23 19:15
@julian-poidevin But you really did an amazing job. You've save a lot of $ !

**Comment by julian-poidevin** [comment] 2017-10-23 19:34
Glad it finally worked. If I saved you the price of a mac please consider paying me a beer via the donation button on the app !😄 🍺

**Comment by mhamzas** [comment] 2017-10-23 20:03
@julian-poidevin I am not gonna pay you for beer. I'll pay you for a Dinner. 🥇

**Comment by julian-poidevin** [comment] 2017-11-03 06:06
@jeromydp Could you get the patch running by following my tips ?

**Comment by julian-poidevin** [comment] 2017-11-16 21:19
@jeromydp Please let me know if it's ok for you, I'll close the issue if I get no news in few days.

**Comment by jeromydp** [comment] 2017-11-16 21:27
Sorry about my delay & thanks for checking in.  I haven’t made time to try it, but my kids remind me regularly about how their MacBook crashes. I’ll make a point to follow your tips tomorrow.

**Comment by jeromydp** [comment] 2017-11-17 01:54
I followed you instructions, reran the patch and it appears to be successful! Do I need to reapply the patch after minor operating system upgrades?

**Comment by julian-poidevin** [comment] 2017-11-17 06:42
Yes, the patch has to be run after *EVERY* OS update.

**Closed by julian-poidevin** 2017-11-17 06:42 UTC
Labels: bug

**Comment by paulywill** [comment] 2018-01-23 19:26
I am having issues as well after upgrading to High Sierra

Trying to test an external projector with HDMI cable is causing random crashes.

**Comment by amordicus** [comment] 2018-10-31 18:30
Bonjour Julian,
I'm not sure you will get this message, since the issue is closed. But I'll comment anyway!
This problem happens when MBPMid2010_GPUFix is ran from a none admin user.  And login into an admin account to run it again doesn't stop the error (Could not open Info.plist file) from happening again, but deleting files from /tmp/ works just fine.

I guess the application should ask for an admin user name!

**Comment by Bl2c5FlA9** [comment] 2018-11-04 19:42
Amordicus-

Thank you for your thoughtful insight.  I followed your procedure and ultimately had success.  I appreciate you taking the time to assist me with this problem!
